### ISSUE TITLE
[Hotfix] 서버 배포 관련하여 논의할 내용

### ISSUE THREAD

**Issue by simhani1** [TeamWazard/wazard-server#207]
- 문제점
  - 지금까지 main 브랜치에 머지를 하고 있었고 배포를 위해 main 브랜치 코드를 서버에서 pull 하여 동작시켰음
  - 그런데 우리가 controller, service, repository 를 따로 작성하고 한번에 main에 머지시키지 않다 보니 service 코드는 있는데 repository 코드는 아직 작성되지 않은 상태로 main에 머지가 되었음
  - 서버에서 스프링을 띄우려고 하니 service 코드에 빈 주입이 제대로 되지 않아 불가능했음 -> repository 구현 코드가 없었기 때문
  - 따라서 **controller, service, repository 가 모두 완성된 코드들만 저장된 배포 전용 브랜치에 대한 필요성을 느낌**

**Comment by min9yu98** [comment]
dev 브랜치로 개발 브랜치 따로 만들고 배포를 main으로
